name = "cloud-note"
main = "src/worker.js"
compatibility_date = "2026-06-01"
workers_dev = true

[[routes]]
pattern = "note.jishu.cc.cd"
custom_domain = true

# D1 数据库绑定
[[d1_databases]]
binding = "NOTE_DB"
database_name = "notes-db"
database_id = "099ff81f-bd87-481d-b561-3deab0ddbde1"

# R2 存储桶绑定（用于图片存储与代理读取）
[[r2_buckets]]
binding = "NOTE_R2"
bucket_name = "notes-db-r2"
